#Server
server:
  port: 8090

#添加Thymeleaf配置
thymeleaf:
  cache: false
  prefix: classpath:/templates/
  suffix: .html
  mode: HTML5
  encoding: UTF-8
  content-type: text/html
#添加redis配置
spring:
  redis:
      #数据库索引
      database: 0
      host: 192.168.56.103
      port: 6379
      password:
      jedis:
        pool:
          #最大连接数
          max-active: 8
          #最大空闲
          max-idle: 8
          #最小空闲
          min-idle: 0
          #连接超时时间
          timeout: 10000
#日志级别
logging:
  level:
    # root日志以WARN级别输出
    root: info
    # 此包下所有class以DEBUG级别输出
    com.cc.owl: error
