thymeleaf:
  cache: false
  prefix: classpath:/templates/
  suffix: .html
  mode: HTML5
  encoding: UTF-8
  content-type: text/html
server:
  port: 8082
  servlet:
    context-path: /wayne
spring:
  mvc:
    date-format: yyyy-MM-dd HH:mm
    hiddenmethod:
      filter:
        enabled: true

#mybatis:
  # 指定全局配置文件位置
#  config-location: classpath:mybatis/mybatis-config.xml
  # 指定sql映射文件位置
#  mapper-locations: classpath:mybatis/mapper/*.xml


